name: Lint On PR

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          mkdir -p "$HOME/bin"
          wget -q https://github.com/ethereum/solidity/releases/download/v0.6.6/solc-static-linux -O $HOME/bin/solc
          chmod u+x "$HOME/bin/solc"
          echo "$HOME/bin" >> $GITHUB_PATH
          solc --version
      - name: Format
        run: cargo fmt
      - name: Lint
        run: cargo clippy
